name: institution_portal
description: A Flutter application for educational institution staff and students

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  qr_flutter: ^4.2.0
  screenshot: ^1.2.3
  path_provider: ^2.1.1
  flutter_svg: ^2.0.7
  firebase_core: ^2.18.0
  firebase_messaging: ^14.7.0
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  lottie: ^2.7.0
  shimmer: ^3.0.0
  flutter_animate: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/